### ISSUE TITLE
List where an add-on is attached

### ISSUE THREAD

**Issue by tt** [heroku/heroku-addon-attachments#10]
I'm trying to deprovision a follower, but I'm blocked as it's attached somewhere. I don't know where, so it would be immensely helpful if some command would allow me to view where a particular add-on instance is attached.

**Comment by bjeanes** [comment]
@tt there has been the `addons:attachments` command for some time. Would grouping things by the add-on make more sense or allow filtering by a specific add-on?

```
$ heroku addons:attachments --all
```

**Comment by tt** [comment]
Sorry for not responding, @bjeanes. That list would be all I need if only it included attachments to unjoined apps.

**Comment by bjeanes** [comment]
@tt ah that's a contentious one. Unfortuntely it's firmly out of scope for now, but the right place for discussion on that is in the API repo. The `GET /addon-attachments` and `GET /addons/:id/addon-attachments` endpoints are scoped to apps you are a collaborator on. The short answer reason is that we don't yet have a way that is both efficient and safe (i.e. not accessing things you shouldn't) to filter by all apps in an org. But... it could be done, if you're game :)

**Comment by tt** [comment]
So how will I know how to deprovision an add-on that's attached somewhere? Can we at least improve that error message and provide a hint about where you need to detach it?

**Comment by bjeanes** [comment]
@tt I opened an issue on API and CC'd you. That's the best place to discuss the issue because it involves a bunch of permissions logic that the orgs team may need to weigh in on.

**Comment by bjeanes** [comment]
To be clear: I agree something needs to change to help that use case. I just need consultation from the orgs team about what is expected here.
