### ISSUE TITLE
This plugin breaks multi-factor authentication

### ISSUE THREAD

**Issue by tt** [heroku/heroku-addon-attachments#12]
% heroku addons
    Two-factor code: ccccccdhtnh.................................
    Two-factor code: ccccccdhtnh.................................
    Two-factor code: ccccccdhtnh.................................
    Two-factor code: ^C !    Command cancelled.
    % heroku plugins:uninstall git@github.com:heroku/heroku-addon-attachments.git
    Uninstalling heroku-addon-attachments... done
    % heroku addons
    Two-factor code: ccccccdhtnh.................................
    === example Configured Add-ons
    ...
    heroku-postgresql:standard-4  HEROKU_POSTGRESQL_NAVY
    heroku-postgresql:standard-5  HEROKU_POSTGRESQL_BROWN

**Comment by bjeanes** [comment]
@tt this is a paranoid app? Maybe the same as #24?

**Comment by tt** [comment]
Yeah.

**Comment by mattreduce** [comment]
@tt @bjeanes I've made an app of mine paranoid so I could try out every one of this plugin's commands and see what's broken for 2fa. https://github.com/heroku/heroku-addon-attachments/commit/9809b4d92e73f4d6300a6eb379508536a9128bda adds `requires_preauth` to each command that needed it. Once that branch is merged, I'll ping you to give this another try.

Thanks for reporting this!

**Comment by mattreduce** [comment]
@tt I've merged the fix for those commands; let me know how you get on now. Thanks again.
