### ISSUE TITLE
Plugin is eating messages from heroku-postgres after creating a new database

### ISSUE THREAD

**Issue by chadbailey59** [heroku/heroku-addon-attachments#13]
When you create a new production-tier database, it isn't available to use for a minute or two. The normal console output looks like this:

```
$ heroku addons:add heroku-postgresql:standard-2 --follow HEROKU_POSTGRESQL_CHARCOAL_URL
Adding heroku-postgresql:standard-2 to sushi... done, v71 ($200/mo)
Attached as HEROKU_POSTGRESQL_WHITE
Follower will become available for read-only queries when up-to-date
Use `heroku pg:wait` to track status
```

However, here's the output from `heroku create` with the plugin:

```
[keycafeweb] (209974) ~/Code/support ▸ heroku addons:create heroku-postgresql:standard-0 --version 9.4 -a cb-rails3Creating maturing-keenly-1246... done
Adding maturing-keenly-1246 to cb-rails3... done
Setting HEROKU_POSTGRESQL_OLIVE_URL and restarting cb-rails3... done, v138
Use `heroku addons:docs heroku-postgresql` to view documentation.
```

No mention of `pg:wait`. When I try to connect immediately, it fails. Can we make sure that post-install messages like these make it through?

**Comment by bjeanes** [comment]
Actually, this is the V3 API which we are necessarily using. See heroku/api#2131 

@geemus has there been a convention for conveying messaging to the client established since that issues last update?

**Comment by bjeanes** [comment]
See also https://github.com/heroku/hk/issues/123#issuecomment-39002182

**Comment by geemus** [comment]
No changes that I'm aware of on that front, we should probably discuss further and decide what we would like to do here soon.

**Comment by bjeanes** [comment]
Indeed. It may be necessary to GA the these CLI changes :/
