### ISSUE TITLE
addons:upgrade does not upgrade

### ISSUE THREAD

**Issue by mathias** [heroku/heroku-addon-attachments#2]
I had to remove the plugin because it cannot upgrade add-ons.

With the plugin enabled:
```
$ heroku addons:upgrade -h
Usage: heroku addons:upgrade ADDON PLAN
 
 upgrade an existing add-on resource to PLAN
 
$ heroku addons:upgrade zerigo_dns 5
Upgrading zerigo_dns to 5... failed
 !    The addon service "5" either doesn't exist or doesn't have a default plan. Please specify a plan.
 
$ heroku addons:upgrade zerigo_dns:5
Upgrading zerigo_dns:5 to ... failed
 !    Couldn't find that add on.
```

When I removed the plugin:
```
$ heroku plugins:uninstall heroku-addon-attachments
Uninstalling heroku-addon-attachments... done

$ heroku addons:upgrade -h
Usage: heroku addons:upgrade ADDON

 upgrade an existing addon

$ heroku addons:upgrade zerigo_dns:5
Upgrading to zerigo_dns:5 on thawing-earth-8791... done, v8 ($5/mo)
Use `heroku addons:docs zerigo_dns` to view documentation.
```

We should look into how to fix the upgrade (potentially downgrade? I didn't try downgrade with this plugin) behavior.

**Comment by mattreduce** [comment]
I can get upgrade to "work" this way:

```sh-session
% h addons:upgrade @memcachier-10051962 memcachier:250 -a provider-summit
Upgrading memcachier-10051962 to memcachier:250... failed
 !    Internal server error.
 !    Run `heroku status` to check for known platform issues.
```

So the syntax is `addons:upgrade <resource name> <addon>:<plan>`. It appears to fail, but it actually succeeds:

```sh-session
% h addons -a provider-summit                                                                                             {1}
=== provider-summit Add-on Resources
heroku-postgresql:hobby-dev  @grinning-freely-1097  DATABASE, HEROKU_POSTGRESQL_VIOLET
memcachier:250               @memcachier-10051964   MEMCACHIER
```

Finding out why. **adventure** :sparkles:

**Comment by bjeanes** [comment]
Yes this is intentional due to the difference in semantics in the V2 and V3 APIs. See [this code](https://github.com/heroku/api/pull/3425/files#diff-5585aad567529e9a6a3e937aa1076c27R131) for some more context, but basically just giving the plan will result in an ambiguous specifier for the add-on that needs to be upgraded. When add-ons where one-per-add-on-type-per-app, this wasn't an issue.

**Comment by bjeanes** [comment]
FWIW, I'd like this to work with just the plan suffix (e.g. `250` instead of `memcachier:250`) since the service name is redundant (though should also be accepted)

**Comment by mattreduce** [comment]
Looks like it's appearing to fail when it succeeds because we expect a 200 response and get 201 :ok:

**Comment by mattreduce** [comment]
>FWIW, I'd like this to work with just the plan suffix (e.g. 250 instead of memcachier:250) since the service name is redundant (though should also be accepted)

+1
