### ISSUE TITLE
Allow users to specify multiple ATTACHMENT_NAMEs

### ISSUE THREAD

**Issue by dgouldin** [heroku/heroku-addon-attachments#20]
I'd like to be able to attach the same add-on in the same app under several different names so that I can decouple the purpose of a config var from its implementation.

In my specific use case, [celery](https://readthedocs.org/projects/celery/) supports multiple message queue brokers, and so it's common to refer to a BROKER_URL config var which could contain a url to redis, rabbitmq, etc. I'd like to be able to use the same redis add-on for my celery broker as for other general redis use but not hard-code my choice of broker into celery.

**Comment by bjeanes** [comment]
This can be done but requires providers to support it. I'm hoping next week to re-work the restriction in API on custom naming to allow it even without the provider opting in to attachments or app multiplicity. More on that soon but if we see one of the Redis providers adopt the new add-on sharing feature set, you'll get this for free anyway.

**Comment by mathias** [comment]
@bjeanes my understanding is that this is an user-specific config var alias. I'm not sure that this is how it'd look for the command invocation, but it'd be something like:

```sh
$ heroku addons:create redisgreen --alias BROKER_URL
Creating redisgreen... done, v3 Adding redisgreen-10070881 to mathias-test... done
Setting REDIS_URL, BROKER_URL and restarting mathias-test... done 
Use `heroku addons:docs redis` to view documentation.
```

where `REDIS_URL` is the same as `BROKER_URL` and `BROKER_URL` wasn't something specified by the provider, and we've set `REDIS_URL`.

The ideal case would be any config var changes to `REDIS_URL` happen to `BROKER_URL` automatically.

**Comment by bjeanes** [comment]
That's equivalent to

``` sh-session
$ heroku addons:create redisgreen --as REDIS_URL --name my-redis
...
$ heroku addons:attach my-redis --as BROKER_URL
...
```

That requires `many_per_app` and `attachable` to day, though there's a case to be made for allowing attachments to the same app (i.e. not-sharing) that is enabled distinctly.

**Comment by mathias** [comment]
:+1: that works too.

**Comment by bjeanes** [comment]
My conservative approach here is that, obviously, this would work fine for data providers to just allow redundant aliases and even cross-app attachments. However, it isn't obvious that such a unilateral distinction would be OK for other types of add-ons, like autoscalers or logging and analytics add-ons. So, I'm content to say that the provider has to say it's ok to have multiple references on an app, at least until we have more data.

**Comment by bjeanes** [comment]
Closing this as there's nothing to do on the plugin about this really. It can be achieved with multiple invocations already but only for add-ons who opt-in to the required feature set.
