### ISSUE TITLE
Output incomplete, interactive confirmation broken for overwriting existing attachments using --as

### ISSUE THREAD

**Issue by mattreduce** [heroku/heroku-addon-attachments#25]
@tt reported this today, and I confirmed using two of my own apps, that the following happens when you try to overwrite:

```
% h addons:attach @drifting-merrily-4727 -a addons-df14 --as DATABASE
Attaching drifting-merrily-4727 as DATABASE to addons-df14... 
 !    drifting-merrily-4727 will overwrite DATABASE_URL on addons-df14.
 !    To proceed, type "" or re-run this command with --confirm 

> addons-df14
 !    Confirmation did not match . Aborted.
```

Using `--confirm APP_NAME` inline does work, however.

**Comment by mathias** [comment]
Should be fixed by https://github.com/heroku/heroku/pull/1410.

**Comment by bjeanes** [comment]
@mathias was it?

**Comment by mattreduce** [comment]
@bjeanes looks like there hasn't been a new Toolbelt release since that commit landed; I tested the latest in `heroku/heroku` locally and confirm it at least fixes the issue there fwiw. Finding out how soon we can get a new release. :boom:

**Comment by bjeanes** [comment]
Ah... I *completely* missed that the other issue was in heroku/heroku haha. No worries :)

**Comment by mathias** [comment]
This works now on the newest Heroku CLI release.
