### ISSUE TITLE
Can't attach resources from other orgs

### ISSUE THREAD

**Issue by idan** [heroku/heroku-addon-attachments#26]
I don't know how realistic this is for our customers.

For the Cost of Services app, I want to be able to attach databases from three different orgs in order to make my stuff immune to credrolls, but I can't, even with sudo powers. :cry: 

Is there a way to make this work?

**Comment by bjeanes** [comment]
There is a feature flag to bypass this validation but is internal only for now. Cross-owner attachments have some serious drawbacks (auditing, visibility, add-on SSO permissions).

**Comment by bjeanes** [comment]
@idan bump! Does the feature flag address your immediate concern? What do you think about the trade-off made here for general availability? As you can imagine, cross-owner attachments require a lot of thoughtful UX and security considerations which we've put out of scope for now.

**Comment by idan** [comment]
Derp, missed this in the mail pile. Feature flag it is, then!

**Comment by bjeanes** [comment]
:+1:
