### ISSUE TITLE
`upgrade` without plan identifier results in 500

### ISSUE THREAD

**Issue by bjeanes** [heroku/heroku-addon-attachments#30]
``` sh-session
$ heroku addons:upgrade newrelic-8895216 -a bjeanes
Upgrading newrelic-8895216 to ... failed
 !    Application error.
```

The CLI should error locally on missing argument or, possibly, offer to upgrade to the next plan level up (or down in case of `downgrade`).

**Comment by mnoble** [comment]
Fix: https://github.com/heroku/heroku-addon-attachments/pull/31
