### ISSUE TITLE
New Relic addon cannot be attached to more than one app

### ISSUE THREAD

**Issue by chibicode** [heroku/heroku-addon-attachments#40]
[The official blog post](https://blog.heroku.com/archives/2015/1/23/expanding_the_power_of_add_ons) says:

> Let’s dig deeper into one example of how add-on sharing gives you this visibility back. One of our most popular add-ons New Relic provides performance monitoring for your application. As your app becomes decomposed you have may have previously had multiple instances of New Relic running attempting to correlate across them. With add-on sharing you’ll be able to simply share your core instance of New Relic to all the other smaller apps and get both a broad but detailed picture into where your performance bottlenecks are.
>
> Here’s what Bill Lapcevic, VP of Customer Success at New Relic, had to say about the new add-on sharing – "New Relic has been an add-on partner from the early days when Heroku pioneered the developer tools ecosystem. We’re excited to be among the first add-on providers to have access to Add-on Sharing, a powerful feature that allows developers to monitor multiple Heroku apps, giving them unprecedented visibility into their environments."

However, when I actually run the `attach` command:

```
# newrelic-xxxxxxx has been added to another app w/ the same owner
$ heroku addons:attach newrelic-xxxxxxx

Attaching newrelic-xxxxxxx to <app name>... failed
 !    That add-on resource is already attached to an app and may only be attached once.
 !    List available resources with `heroku addons`.
 !    Provision a new add-on resource with `heroku addons:create ADDON_PLAN`.
```

I was able to attach postgres to more than one apps using the same method.

**Comment by bjeanes** [comment]
@chibicode New Relic has not enabled this feature yet. They are doing further testing. The blog post was using New Relic to highlight the types of use cases this feature will enable and they'll be an early adopter of the feature, but that might still be a couple of weeks ago at least. Sorry for the confusion.

**Comment by chibicode** [comment]
Got it, sorry I didn't read carefully.

**Comment by isTravis** [comment]
A few years later, and it seems New Relic still does not support attaching to more than on app. Is this the final decision on the matter?

**Comment by bjeanes** [comment]
(note: I no longer work at Heroku or on add-ons in any way so this is not an official response)

This is something that you need to talk to New Relic about. They are responsible for the integration which would enable this capability and not something Heroku can decide for them.
