### ISSUE TITLE
addons:add does not attach

### ISSUE THREAD

**Issue by mathias** [heroku/heroku-addon-attachments#9]
I'll add more details tomorrow. Log of context:

```
$ heroku addons --app young-garden-2012
=== young-garden-2012 Add-on Resources
slowdb:test  @cooking-simply-4450  SLOWDB_AMBER
slowdb:test  @flying-deeply-6933   PRODUCT_DATABASE

$ heroku addons --app mathias-test
=== mathias-test Add-on Resources
deployhooks:email  @deployhooks-email-10044693  DEPLOYHOOKS_EMAIL

$ heroku addons:add @cooking-simply-4450 --app mathias-test
Adding cooking-simply-4450 to mathias-test... failed
 !    Add-on resource `cooking-simply-4450` not found.
 !    List available resources with `heroku addons:resources`.
 !    Provision a new add-on resource with `heroku addons:create `.

$ heroku addons:add cooking-simply-4450 --app mathias-test
Adding cooking-simply-4450 to mathias-test... failed
 !    Add-on resource `cooking-simply-4450` not found.
 !    List available resources with `heroku addons:resources`.
 !    Provision a new add-on resource with `heroku addons:create `.
```

**Comment by bjeanes** [comment]
Does it work with HPG?

**Comment by mattreduce** [comment]
@bjeanes @mathias it doesn't work for me with HPG:

```
% h addons -a matthewconway                      
=== matthewconway Add-on Resources
heroku-postgresql:hobby-dev  @relaxing-avidly-3674  DATABASE, HEROKU_POSTGRESQL_BLUE

% h addons:add @relaxing-avidly-3674 -a conway-test
Adding relaxing-avidly-3674 to conway-test... failed
 !    Add-on resource `relaxing-avidly-3674` not found.
 !    List available resources with `heroku addons:resources`.
 !    Provision a new add-on resource with `heroku addons:create `.
```

**Comment by bjeanes** [comment]
Well that's a problem. This seems new, no? Maybe some recent changes to these APIs? Maybe something like heroku/api#3414 (guess in the dark)?

**Comment by mattreduce** [comment]
@bjeanes I had forgotten about Direwolf specs up to this point, but I see now it's probably worth it to have at least a separate suite running through these commands... haven't dug into why this is failing just yet, though

**Comment by mathias** [comment]
We were able to demo this functionality in the past, so yes, it must be a
regression since that point.

On Wed, Jan 14, 2015 at 6:42 PM, Matthew Conway <notifications@github.com>
wrote:

> @bjeanes <https://github.com/bjeanes> I had forgotten about Direwolf
> specs up to this point, but I see now it's probably worth it to have at
> least a separate suite running through these commands... haven't dug into
> why this is failing just yet, though
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/heroku-addon-attachments/issues/9#issuecomment-70021406>
> .
>



-- 
Matt Gauger

**Comment by mathias** [comment]
This is also true for Heroku Postgresql.

**Comment by mathias** [comment]
The error message in my first log is misleading. It is getting back a 422 with a gzipped response body, but when I curled the same endpoint, I got

```json
{
    "id": "invalid_params",
    "message": "That add-on resource is already attached to an app and may only be attached once. "
}
```

Turns out that the SlowDB add-on I'd created for env never got `many_per_app` or `attachable` features.

I think at least part of this work is handling a 422 with that body to say that the add-on cannot attach to multiple apps rather than saying `Add-on resource `cooking-simply-4450` not found.`

**Comment by mathias** [comment]
So this works if the add-on is attachable.

The solution is to improve the error message.

**Comment by mattreduce** [comment]
@mathias ah that's good news!

**Comment by bjeanes** [comment]
@mathias indeed, I think some of the changes in heroku/api#3425 will help that, hopefully.
